---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ file_path }}"
    state: directory
    mode: "775"
    recurse: true

- name: Include selinux role
  vars:
    selinux_fcontexts:
      - {target: '{{ file_path }}(/.*)?', setype: 'httpd_sys_content_t', state: 'present'}
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.selinux

- name: Ensure Nginx container is running
  containers.podman.podman_container:
    name: nginx_container
    image: docker.io/nginx:stable-alpine3.17-slim
    state: started
    ports:
      - "{{ web_port }}:80"
    volumes:
      - "{{ file_path }}:/usr/share/nginx/html:Z"
    recreate: true

- name: Create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/index.html"
    mode: "644"

- name: Copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "775"

- name: Copy images over
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "644"
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"

- name: Check if customer logo exists
  ansible.builtin.stat:
    path: "{{ role_path }}/files/{{ customer_logo }}"
  register: logo_file
  delegate_to: localhost
  when: 
    - show_customer_logo | default(false)
    - customer_logo is defined

- name: Copy customer logo if exists
  ansible.builtin.copy:
    src: "{{ customer_logo }}"
    dest: "{{ file_path }}/{{ customer_logo }}"
    mode: "644"
  when: 
    - show_customer_logo | default(false)
    - customer_logo is defined
    - logo_file.stat.exists | default(false)

- name: Display logo status
  ansible.builtin.debug:
    msg: "Note: Customer logo file '{{ customer_logo }}' not found. Add it to roles/build_report_container/files/ to display logo."
  when:
    - show_customer_logo | default(false)
    - customer_logo is defined
    - not (logo_file.stat.exists | default(false))

- name: Retrieve public IP address
  ansible.builtin.command: curl https://ifconfig.me
  register: public_ip_report
  ignore_errors: true

- name: Display link to inventory report
  ansible.builtin.debug:
    msg:
      - "Please go to http://{{ public_ip_report.stdout | default(ansible_fqdn) }}:{{ web_port }}"
