---
- name: Gather cisco ios facts including interface status
  cisco.ios.ios_facts:
    gather_subset: 
      - config
      - interfaces
    gather_network_resources: "{{ network_resource | default('all') }}"

- name: Store interface operational status
  ansible.builtin.set_fact:
    interface_status: "{{ ansible_net_interfaces | default({}) }}"
