---
- name: Gather juniper junos facts including interface status
  junipernetworks.junos.junos_facts:
    gather_subset: 
      - config
      - interfaces
    gather_network_resources: "{{ network_resource | default('all') }}"

- name: Store interface operational status
  ansible.builtin.set_fact:
    interface_status: "{{ ansible_net_interfaces | default({}) }}"
